runtime: nodejs20

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  STRIPE_PUBLISHABLE_KEY: "pk_live_51RJyu7H56GWeesIThVgLHAHXKv1GrWrhTNEEuZULBjjFMQlx4PWAKPCLI1ALjLwxYCRFQnpA40XwAjgcdeXWGXoa00XsoIA5oQ"
  STRIPE_SECRET_KEY: "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"
  SESSION_SECRET: "daswos-production-session-secret-key"
  # You'll need to update this with your actual database connection string
  DATABASE_URL: "postgresql://neondb_owner:npg_j1h0TMQzEWpR@ep-rapid-tree-a2njogo6-pooler.eu-central1.aws.neon.tech/neondb?sslmode=require"
  CLIENT_URL: "https://daswos.appspot.com"

handlers:
  # Serve static files
  - url: /static
    static_dir: dist/public
    secure: always

  # Serve all other routes through the Node.js application
  - url: /.*
    script: auto
    secure: always

instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
