version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ..:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    command: sleep infinity
    networks:
      - trustsphere
    depends_on:
      db:
        condition: service_healthy

networks:
  trustsphere:
    external: true